### ISSUE TITLE
The new version is not working and unable to download

### ISSUE THREAD

**Issue by lydiachang2017** [Displayr/flipFormat#1]
The new version of flip format causes HTTP 404 error when trying to install the package

**Comment by mwmclean** [comment]
Is [this](https://github.com/r-lib/remotes/issues/210) the issue you're seeing? Has to do with an update to the `devtools` package.

**Comment by JoseAlanis** [comment]
Hey guys, I know the issue is closed, but I'm getting the same `HTTP error 404. Not Found`, even after setting the `dependencies = NA` argument.
Any suggestions?

**Comment by mwmclean** [comment]
Yes, sorry, I filed an Issue with the `devtools` maintainers as it looks like a bug on their end. For now you can either install an older version of `flipFormat` before the private package was added to `Suggests`:
```
devtools::install_github("Displayr/flipFormat@fdb86b6")
```
or install all required dependencies with calls to `install.packages()` and `install_github()` and then use
```
devtools::install_github("Displayr/flipFormat", dependencies = FALSE)
```
to get the latest version of the package.

**Comment by JoseAlanis** [comment]
ok, cool thanks.  I managed to install the packages by installing the dependencies by hand and then running `devtools::install_github()` with `dependecies=FALSE`
